import os
import html as ihtml
from datetime import datetime
from colorama import Fore
from Utils.logger_config import get_logger

# Initialize logger for this module
logger = get_logger(__name__)


def render_html(results, config):
    """Generate full Secure Release HTML report."""
    logger.info("Starting HTML report generation")
    
    # --- Metadata extraction ---
    tool_info = config.get("tool_info", {})
    report_info = config.get("report", {})
    project = config.get("Assessment_Project_Details", {})

    company = tool_info.get("company_name", "Your Company")
    title = report_info.get("report_header", "Secure Release")
    report_type = report_info.get("report_title", "SAST Report")
    footer = report_info.get("report_footer", "Generated by Secure Release")
    year = tool_info.get("year", "2025")

    timestamp = datetime.now().strftime("%A %d-%b-%Y %H:%M:%S")
    app_name = project.get("name", "Project")
    app_version = project.get("version", "1.0.0")
    app_technology = project.get("technology", "N/A")
    
    logger.debug(f"Report metadata - App: {app_name}, Version: {app_version}, Tech: {app_technology}")

    # --- Issue collection ---
    issues = {
        "Secret Scanner": results.get("Secret Scanner", []),
        "Code Analyzer": results.get("Code Analyzer", []),
        "Dependency Scan": results.get("Dependency Scan", []),
    }
    
    # Calculate totals
    issue_counts = {k: len(v) for k, v in issues.items()}
    total_findings = sum(issue_counts.values())
    
    logger.info(f"Report statistics - Total: {total_findings}, Breakdown: {issue_counts}")

    # --- CSS Styling ---
    css = """
    body {
        font-family: 'Inter', Arial, sans-serif;
        background: #eef2ff;
        color: #1e293b;
        margin: 0;
        padding: 30px;
    }
    .container {
        max-width: 1200px;
        margin: auto;
        background: #ffffff;
        border-radius: 16px;
        padding: 25px 30px;
        box-shadow: 0 4px 18px rgba(0, 0, 0, 0.08);
    }
    .header {
        background: linear-gradient(90deg, #2563eb, #3b82f6);
        color: white;
        border-radius: 15px;
        padding: 10px;
        text-align: center;
        box-shadow: 0 4px 12px rgba(59, 130, 246, 0.25);
    }
    .header h1 { font-size: 35px; margin: 0; font-weight: 800; }
    .header h1 span.emoji { font-size: 40px; }

    .subheader {
        background: #c9d6f7;
        border: 1px solid #e2e8f0;
        border-radius: 10px;
        padding: 15px;
        margin-top: 5px;
        text-align: center;
        box-shadow: 0 2px 8px rgba(0,0,0,0.05);
    }
    .subheader h2 {
        color: #1e3a8a; margin: 0 0 8px;
        font-size: 22px; font-weight: 700;
    }
    .subheader h4 {
        color: #475569; margin: 4px 0 0; font-size: 15px;
    }
    .timestamp {
        font-size: 14px; text-align: right;
        color: #64748b; margin-top: 10px;
    }
    .section {
        margin-top: 28px; border-radius: 12px;
        border: 1px solid #e2e8f0; background: #fff;
        overflow: hidden; box-shadow: 0 2px 10px rgba(0,0,0,0.04);
    }
    .section-title {
        padding: 12px 18px; font-weight: 700;
        font-size: 18px; display: flex; align-items: center;
        gap: 8px; color: white;
    }
    .sec-secret { background: linear-gradient(90deg, #06b6d4, #0ea5e9); }
    .sec-code   { background: linear-gradient(90deg,#10b981,#34d399); }
    .sec-dep    { background: linear-gradient(90deg, #8b5cf6, #a78bfa); }

    .card { padding: 18px; }
    .item {
        border: 1px solid #e2e8f0; border-radius: 8px;
        padding: 12px 14px; margin-bottom: 10px;
        background: #f9fafb; transition: box-shadow 0.2s ease;
    }
    .item:hover { box-shadow: 0 2px 8px rgba(0,0,0,0.1); }

    .k {
        display: inline-block; width: 160px;
        color: #580202; font-weight: 600;
        vertical-align: top;
    }
    .value {
        display: inline-block; width: calc(100% - 170px);
        vertical-align: top; word-wrap: break-word; white-space: pre-wrap;
    }

    .sev-critical, .sev-high, .sev-error, .sev-warning, .sev-medium,
    .sev-low, .sev-info, .sev-unknown {
        padding: 2px 8px; border-radius: 6px;
        font-weight: 700; font-size: 13px;
        line-height: 1.4; display: inline-block; vertical-align: middle;
    }

    .sev-critical { background: #dc2626; color: #fff; }
    .sev-high     { background: #f87171; color: #1e293b; }
    .sev-error    { background: #f97316; color: #fff; }
    .sev-warning  { background: #facc15; color: #78350f; }
    .sev-medium   { background: #fde68a; color: #1e293b; }
    .sev-low      { background: #bbf7d0; color: #064e3b; }
    .sev-info     { background: #bfdbfe; color: #1e3a8a; }
    .sev-unknown  { background: #e5e7eb; color: #374151; }

    footer {
        text-align: center; background: #2563eb;
        color: white; font-weight: 600;
        border-radius: 8px; margin-top: 35px;
        padding: 10px; box-shadow: 0 4px 10px rgba(37,99,235,0.3);
    }
    """

    logger.debug("Building HTML structure")

    # --- HTML Header ---
    html = f"""<!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width,initial-scale=1.0">
        <title>{title} - {report_type}</title>
        <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;600;800&display=swap" rel="stylesheet">
        <style>{css}</style>
    </head>
    <body>
    <div class="container">
        <div class="header"><h1><span class="emoji">🕵️</span> {title}</h1></div>
        <div class="subheader">
            <h2>📊 {report_type} - Total Findings ({total_findings})</h2>
            <h4>Application Name: {app_name} | Version: {app_version} | Technology: {app_technology}</h4>
        </div>
        <div class="timestamp">🕐 Report Generated: {timestamp}</div>
    """

    # --- Helper: Render field/value HTML ---
    def render_field(k, v):
        """Return formatted HTML for a key-value field."""
        if isinstance(v, (dict, list)):
            v = ", ".join(set(v)) if k.lower() == "advisory ids" else str(v)
        v = ihtml.escape(str(v))
        if k.lower() in ("severity", "impact"):
            return f'<div><span class="k">{k.capitalize()}:</span><span class="value"><span class="sev-{v.lower()}">{v}</span></span></div>'
        return f'<div><span class="k">{k.capitalize()}:</span><span class="value">{v}</span></div>'

    # --- Helper: Deduplicate dependency scan ---
    def deduplicate_issues(section_issues):
        logger.debug(f"Deduplicating {len(section_issues)} dependency issues")
        deduped = {}
        for issue in section_issues:
            key = (issue.get("package", ""), issue.get("current ver", ""),
                   issue.get("recommended ver", ""), issue.get("file", ""))
            if key not in deduped:
                deduped[key] = {**issue, "advisory ids": [issue.get("advisory id", "")]}
            else:
                deduped[key]["advisory ids"].append(issue.get("advisory id", ""))
        logger.debug(f"After deduplication: {len(deduped)} unique issues")
        return list(deduped.values())

    # --- Generic section rendering ---
    def render_section(name, section_issues, icon, css_class, dedup=False):
        nonlocal html
        logger.debug(f"Rendering section: {name} with {len(section_issues)} issues")

        # data = deduplicate_issues(section_issues) if dedup else section_issues
        
        html += f'<div class="section">'
        html += f'<div class="section-title {css_class}">{icon} {name} ({len(section_issues)})</div><div class="card">'

        if not section_issues:
            html += '<div class="item">✅ No issues found.</div></div></div>'
            logger.debug(f"Section {name} has no issues")
            return

        for issue in section_issues:
            html += '<div class="item">' + "".join(render_field(k, v) for k, v in issue.items()) + '</div>'
        html += '</div></div>'

    # --- Render each section ---
    render_section("Secret Scanner", issues["Secret Scanner"], "🔒", "sec-secret")
    render_section("Code Analyzer", issues["Code Analyzer"], "🧑‍💻", "sec-code")
    render_section("Dependency Scan", issues["Dependency Scan"], "📚", "sec-dep", dedup=True)

    # --- Footer ---
    html += f"""
        <footer>{footer} &middot; © {year} {company}</footer>
    </div></body></html>
    """
    
    logger.info("HTML report generation completed successfully")
    return html


def generate(results, config):
    """Save generated HTML report to file."""
    logger.info("Generating HTML report")
    
    report_dir = config.get("report_dir", "./reports")
    logger.debug(f"Report directory: {report_dir}")
    
    try:
        os.makedirs(report_dir, exist_ok=True)
        logger.debug(f"Ensured report directory exists: {report_dir}")

        report_path = os.path.join(report_dir, "security_report.html")
        html_content = render_html(results, config)

        with open(report_path, "w", encoding="utf-8") as f:
            f.write(html_content)

        logger.info(f"HTML report successfully written to: {report_path}")
        print(Fore.LIGHTMAGENTA_EX + f"\n[+] HTML report generated at: {report_path}", flush=True)
        
    except Exception as e:
        logger.error(f"Failed to generate HTML report: {str(e)}", exc_info=True)
        print(Fore.RED + f"[!] Error generating HTML report: {str(e)}" + Fore.RESET)
