import os
import html as ihtml
from datetime import datetime
from colorama import Fore

def render_html(results, config):
    company = config.get("tool_info", {}).get("company_name", "Your Company")
    title = config.get("report", {}).get("report_header", "Secure Release")
    report_type = config.get("report", {}).get("report_title", "SAST Report")
    timestamp = datetime.now().strftime("%A %d-%b-%Y %H:%M:%S")
    app_name = config.get("Assessment_Project_Details", {}).get("name", "Project")
    app_version = config.get("Assessment_Project_Details", {}).get("version", "1.0.0")
    app_technology = config.get("Assessment_Project_Details", {}).get("technology", "N/A")
    footer = config.get("report", {}).get("report_footer", "Generated by Secure Release")
    year = config.get("tool_info", {}).get("year", "2025")

    issues = {
        "Secret Scanner": results.get("Secret Scanner", []),
        "Code Analyzer": results.get("Code Analyzer", []),
        "Dependency Scan": results.get("Dependency Scan", [])
    }

    total_findings = sum(len(v) for v in issues.values())

    # 🎨 Modern, professional CSS theme
    css = """
    body {
        font-family: 'Inter', Arial, sans-serif;
        background: #eef2ff; /* soft pastel background */
        color: #1e293b;
        margin: 0;
        padding: 30px;
    }
    .container {
        max-width: 1200px;
        margin: auto;
        background: #ffffff;
        border-radius: 16px;
        padding: 25px 30px;
        box-shadow: 0 4px 18px rgba(0, 0, 0, 0.08);
    }

    /* --- HEADER --- */
    .header {
        background: linear-gradient(90deg, #2563eb, #3b82f6);
        color: white;
        border-radius: 15px;
        padding: 10px 10px;
        text-align: center;
        vertical-align: middle;
        box-shadow: 0 4px 12px rgba(59, 130, 246, 0.25);
    }
    .header h1 {
        font-size: 35px;
        margin: 0;
        font-weight: 800;
    }
    .header h1 span.emoji {
        font-size: 40px;
    }

    /* --- SUBHEADER --- */
    .subheader {
        background: #c9d6f7;
        border: 1px solid #e2e8f0;
        border-radius: 10px;
        padding: 15px 15px;
        margin-top: 5px;
        text-align: center;
        box-shadow: 0 2px 8px rgba(0,0,0,0.05);
    }
    .subheader h2 {
        color: #1e3a8a;
        margin: 0 0 8px;
        font-size: 22px;
        font-weight: 700;
    }
    .subheader h4 {
        color: #475569;
        margin: 4px 0 0;
        font-size: 15px;
    }

    .timestamp {
        font-size: 14px;
        text-align: right;
        color: #64748b;
        margin-top: 10px;
    }

    /* --- SECTION STYLING --- */
    .section {
        margin-top: 28px;
        border-radius: 12px;
        border: 1px solid #e2e8f0;
        background: #ffffff;
        overflow: hidden;
        box-shadow: 0 2px 10px rgba(0,0,0,0.04);
    }
    .section-title {
        padding: 12px 18px;
        font-weight: 700;
        font-size: 18px;
        display: flex;
        align-items: center;
        gap: 8px;
        color: white;
    }
    .sec-secret { background: linear-gradient(90deg, #06b6d4, #0ea5e9); }
    .sec-code   { background: linear-gradient(90deg,#10b981,#34d399); }
    .sec-dep    { background: linear-gradient(90deg, #8b5cf6, #a78bfa); }

    .card { padding: 18px; }
    .item {
        border: 1px solid #e2e8f0;
        border-radius: 8px;
        padding: 12px 14px;
        margin-bottom: 10px;
        background: #f9fafb;
        transition: box-shadow 0.2s ease;
    }
    .item:hover { box-shadow: 0 2px 8px rgba(0,0,0,0.1); }

    .k {
        display: inline-block;
        width: 160px;
        color: #580202;
        font-weight: 600;
    }

    .sev-critical, .sev-high, .sev-warning, .sev-medium, .sev-low, .sev-info, .sev-unknown {
        padding: 2px 8px;
        border-radius: 6px;
        font-weight: 700;
        font-size: 13px;
    }
 
    .sev-critical { background: #dc2626; color: #ffffff; }   /* Deep Red */
    .sev-high     { background: #f87171; color: #1e293b; }   /* Light Red */
    .sev-warning  { background: #facc15; color: #78350f; }   /* Amber/Yellow Warning */
    .sev-medium   { background: #fde68a; color: #1e293b; }   /* Soft Yellow */
    .sev-low      { background: #bbf7d0; color: #064e3b; }   /* Green */
    .sev-info     { background: #bfdbfe; color: #1e3a8a; }   /* Blue Info */
    .sev-unknown  { background: #e5e7eb; color: #374151; }   /* ⚪ Unknown - Neutral Gray */

    footer {
        text-align: center;
        background: #2563eb;
        color: white;
        font-weight: 600;
        border-radius: 8px;
        margin-top: 35px;
        padding: 10px;
        box-shadow: 0 4px 10px rgba(37, 99, 235, 0.3);
    }
    """

    html = f"""<!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width,initial-scale=1.0">
        <title>{title} - {report_type}</title>
        <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;600;800&display=swap" rel="stylesheet">
        <style>{css}</style>
    </head>
    <body>
    <div class="container">
        <div class="header">
            <h1><span class="emoji">🕵️</span> {title}</h1>
        </div>

        <div class="subheader">
            <h2>📊 {report_type} - Total Findings ({total_findings})</h2>
            <h4>Application Name: {app_name} | Version: {app_version} | Technology: {app_technology}</h4>
        </div>

        <div class="timestamp">
            🕒 Report Generated: {timestamp}
        </div>
    """

    # --- Render each section ---
    def render_section(name, section_issues, icon, css_class):
        nonlocal html
        html += f'<div class="section">'
        html += f'<div class="section-title {css_class}">{icon} {name} ({len(section_issues)})</div>'
        html += '<div class="card">'
        if not section_issues:
            html += '<div class="item">✅ No issues found.</div>'
        for issue in section_issues:
            html += '<div class="item">'
            for k, v in issue.items():
                if isinstance(v, (dict, list)):
                    v = str(v)
                v = ihtml.escape(str(v))
                if k.lower() in ("severity", "impact"):
                    html += f'<div><span class="k">{k.capitalize()}:</span> <span class="sev-{v.lower()}">{v}</span></div>'
                else:
                    html += f'<div><span class="k">{k.capitalize()}:</span> {v}</div>'
            html += '</div>'
        html += '</div></div>'

    render_section("Secret Scanner", issues["Secret Scanner"], "🔑", "sec-secret")
    render_section("Code Analyzer", issues["Code Analyzer"], "🧑‍💻", "sec-code")
    render_section("Dependency Scan", issues["Dependency Scan"], "📚", "sec-dep")

    html += f"""
        <footer>
            {footer} &middot; © {year} {company}
        </footer>
    </div>
    </body></html>
    """

    return html


def generate(results, config):
    report_dir = config.get("report_dir", "./reports")
    os.makedirs(report_dir, exist_ok=True)
    report_path = os.path.join(report_dir, "security_report.html")

    html_content = render_html(results, config)
    with open(report_path, "w", encoding="utf-8") as f:
        f.write(html_content)

    print(Fore.LIGHTMAGENTA_EX + f"\n[+] HTML report generated at: {report_path}", flush=True)
